/// Flutter icons ChatBot
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
// /   fonts:
// /    - family:  ChatBot
// /      fonts:
// /       - asset: fonts/ChatBot.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ChatBot {
  ChatBot._();

  static const _kFontFam = 'ChatBot';
  static const String? _kFontPkg = null;

  static const IconData boticons = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
